# PROJECT IN MAA700 OPTIMIZATION
# Teacher Daniel Andrèn

## 1)State the Problem

We consider a portfolio problem with $n$ different assets or stocks held over a time period. We denote $x_i$ the amount of asset $i$ held throughout the period at the price at the beginning of the period. We let $p_i$ denotes the relative price change of asset $i$ over the period. We know the relative price is the change in price over the period divided by its price at the beginning of the period. The overall return on the portfolio is $r = p^Tx$ (in dollars). The optimization variable is the portfolio vector $x∈R^n$. The constraint in the problem is $1^Tx = b$ which means the total budget to be invested is $b$ and it is 1. The price changes $p∈R^n$ is a random vector with known mean $\overline{p}$ and covariance $ \Sigma$. Therefore with portfolio $x∈R^n$ the return $r$ is a random variable with mean $p^Tx$ and variance $x^T \Sigma x$. The choice of portfolio $x$ involves a trade-off between the mean of the return, and its variance.

The term portfoilio means collection of financial investments like assets or stocks. The portfolio return means the gain or loss that is realized by investmenting in a portfolio. The term mean return is also known as an expected return and it shows how much a stock returns over a specific time period. Variance is an important metric in the investment and it is the volatility which is a measure of risk. 
We said we want to maximize the mean return and minimize the variance; which means we want to increase the mean value of possible returns and decrease the risk. The portoflio optimization problem is QP (quadratic progem):

$$  minimize \ \ \ \ \  \ \ \ \ \ \ \ \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ \overline{p}^Tx +ux^T \Sigma x$$
$$  subject \ \ to \ \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 1^T\cdot x = 1 $$
$$    \ \ \ \ \  \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ x\geq 0 $$

where $x$, the portfolio is a variable. We want to maximize mean return and minimize the return variance where the optimization variable is the portfolio vector $x$.  In forming the the associated scalarized problem, we can (without loss of generality) take $\lambda_1 = 1$ and $\lambda_2 = u > 0$.
The standard equality constrained problem is:
$$   minimize \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ f(x)  $$
$$   Subject \ \ to \ \ \ \ \  \ \ \ \ \ \ Ax=b $$

$$  \ \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ Ax = b $$
where $A  = 1^T$ which is an array and $b = 1$
$$  \ \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 1^Tx = b $$
The total budget to b invested is $b$. The $b$ is often taken as $1$.This indicates that the total weigth cannot be over 1.
$$  \ \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 1^Tx = 1 $$

The constraints can be expressed as:
$$A=\begin{bmatrix} 
\mathbb1 
\end{bmatrix},
x=\begin{bmatrix}
x\\
\end{bmatrix}, 
b=\begin{bmatrix}
1
\end{bmatrix}$$



We have three assets which means $n = 3$. The A matrix is:
$$A=\begin{bmatrix} 
1 & 1 &1
\end{bmatrix}$$

## 2)Formulate a mathematical model of the problem

As mentioned the problem is quadratic optimization problem with the following variables:


$x =$ optimal portfolio vector


$p = $  relative price change 


$\overline{p} =$ mean return for random variable $p$


$ \Sigma =$ covariance  for random variable $p$


$\overline{p}^Tx$ = expected return for portfolio $x∈R^n$


$x^T \Sigma x$ = variance for portfolio $x∈R^n$


$r = p^Tx$ = portfolio return

## 3)Prove the model to be a convex optimization problem

The problem is convex optimization with inequality and equality constraints and



1) The objective function $f(x)$ is twice diffferentiable and quadratic.



2) Hessian $H = 2u \Sigma \geq 0$.



3) The equaltiy constraint function $1^T\cdot x-1 = 0$ is affine.

# 4)Formulate the Lagrange dual problem

The lagrangian dual function $g$ is the infimum of the Lagrangian over $x$

$g(\lambda,v) = infL \left (x,\lambda,v) = inf(f_0(x)+ \sum_{i=1}^m\lambda_if_i(x)+ \sum_{i=1}^mv_ih_i(x) \right )$


As the dual function is the pointwise infimum of a family of affine functions of $(\lambda,v)$, it is concave. 

We have inequality constraint function and $f_i(x)= -x_i, i = 1,...,n $. To form the Lagrangian we introduce multipliers $\lambda_i$ for $n$ inequality constraints and multiplier $v_i$ for the equality constraints, and obtain

$L(x,\lambda,v) =  -\overline{p}^Tx +ux^T \sum x-\sum_{i=1}^m\lambda_ix_i+v(1^T \cdot x-1)$

We will take the derivative with respect to $x$ to solve for the minimum value with no constraints

$\bigtriangledown L(x,\lambda,v)= 2u\Sigma x-\overline{p}-\lambda+v \cdot 1 =0 $

Solve for $x$

$x = \frac {1}{2u}\Sigma^{-1}(\overline{p}+\lambda-v \cdot 1)$



The dual function is:

$g(\lambda,v) =L (\frac {1}{2u}\Sigma^{-1}(\overline{p}+\lambda-v \cdot 1), \lambda ,v)$

$= -\overline{p}^T \left(\frac {1}{2u}\Sigma^{-1}(\overline{p}+\lambda-v \cdot 1)\right)+u(\frac {1}{2u}\Sigma^{-1}(\overline{p}+\lambda-v \cdot 1)^T \Sigma \left(\frac {1}{2u}\Sigma^{-1}(\overline{p}+\lambda-v \cdot 1)\right)- \sum_{i=1}^m\lambda_i (\frac {1}{2u}\Sigma^{-1}(\overline{p}+\lambda-v \cdot 1))+v^T \cdot 1 \left(\frac {1}{2u}\Sigma^{-1}(\overline{p}+\lambda-v \cdot 1)\right) - v \cdot 1$


$= \frac {1}{4u}(\overline{p}+\lambda-v \cdot 1)^T \Sigma^{-1}(\overline{p}+\lambda-v \cdot 1)- \frac {1}{2u}(\overline{p}+\lambda-v \cdot 1)^T \Sigma^{-1}(\overline{p}+\lambda-v \cdot 1)- v \cdot 1$

$=  -\frac {1}{4u}(\overline{p}+\lambda-v \cdot 1)^T \Sigma^{-1}(\overline{p}+\lambda-v \cdot 1) - v \cdot 1$

The dual problem can be written as:

$$ maximize \ \ \ \ \ \ \ \ \ \  -\frac {1}{4u}\left(\overline{p}+\lambda-v \cdot 1 \right)^T \sum^{-1}\left(\overline{p}+\lambda-v \cdot 1 \right) - v \cdot 1$$

$$   subject \ \ to \ \ \ \ \  \ \ \ \ \ \ \ \ \ \lambda \geq 0 $$

## 5)Implement a method for solving the problem

We will use interior-point methods which is to solve an optimization problem with equality and inequality constraints and our goal is to apply Newton’s method to a sequence of equality constrained problems. Therefore  we need to formulate the inequality constraint problem as an equality constraint problem after which we can use Newton’s
method. We will start to rewrite the problem using logarithmic barrier method.


 $$   minimize \ \ \ \ \ \ \ \ \ \ \ t f_0(x) + \Phi(x)$$
 $$  subject \ \ to\ \ \ \ \ \ \ \ \ \ \ 1^T  \cdot x =1$$
 
 where
 
 
 $$\Phi(x) = -\sum_{i=1}^m \log (-f_i(x))=- \sum_{i=1}^m \log (x))$$
 
  $$  minimize \ \ \ \ \ \ f_0(x) =t(\overline{p}^Tx +ux^T \sum x)- \sum_{i=1}^m \log (x)) $$
 $$  subject\ \ to\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  1^T  \cdot x =1$$
 
 
 $$\bigtriangledown f_0(x)=- t\overline{p} +2tu \sum x - \frac {1}{x}= gradient$$
 
 $$\bigtriangledown^2 f_0(x) = 2tu \sum +diag\frac {1}{x^2} = Hessian $$

For equality constrained quadratic problem the Newton step is characterized by


$$\begin{bmatrix}
\bigtriangledown^2 f_0(x) & A^T\\
A & 0\\
\end{bmatrix} \begin{bmatrix}
\Delta x_n\\
v\\
\end{bmatrix}=\begin{bmatrix}
-\bigtriangledown f_0(x)\\
0\\
\end{bmatrix}$$



$$\begin{bmatrix}
2tu \Sigma +diag\frac {1}{x^2}  & 1\\
1^T & 0\\
\end{bmatrix} \begin{bmatrix}
\Delta x_n\\
v\\
\end{bmatrix}=\begin{bmatrix}
-g\\
0\\
\end{bmatrix}$$


$$\begin{bmatrix}
H  & 1\\
1^T & 0\\
\end{bmatrix} \begin{bmatrix}
\Delta x_n\\
v\\
\end{bmatrix}=\begin{bmatrix}
-g\\
0\\
\end{bmatrix}$$

we know $H$ is Hessian and $g$ is gradient in the matrix. Now we will find $ \Delta x_n$ and $v$. The $v$ is optimal dual variable for quadratic problem. The $x + \Delta x $ should be a good estimate of the minimizer of $f$ i.e. $x$. Since $f$ is twice differentiable, the quadratic model of $f$ will be very accurate. 


We have two equation:


$$ H \cdot \Delta x_n + 1 \cdot v = -g   $$ 
$$ 1^T \cdot \Delta x_n = 0  $$



using $H\cdot \Delta x_n + 1 \cdot v = -g  $ we will solve for $\Delta x_n$


$$H \cdot \Delta x_n + 1 \cdot v = -g $$

$$H \cdot \Delta x_n +  = -1 \cdot v-g $$

$$\Delta x_n = -H^{-1}(1 \cdot v +g)$$







using $1^T \cdot \Delta x_n = 0   $ we will solve for $v$


$$1^T \cdot \Delta x_n = 0  $$


Using $\Delta x_n = -H^{-1}(1 \cdot v +g)$



$$1^T(H^{-1}(1\cdot v +g)) = 0$$


$$v = \frac {-(1 \cdot  H^{-1} \cdot g)}{(1^T \cdot  H^{-1} \cdot 1)}$$



$$v = -( 1^T \cdot H^{-1} \cdot 1)^{-1}(1 \cdot H^{-1} \cdot g)$$


We have all optimal portfolios except for the two limiting cases corresponding to $u \rightarrow 0$ and $u \rightarrow \infty$. We can say in the first case we get a maximum mean return, without regard for return variance;
in the second case we form a minimum variance return, without regard for mean
return.



# 6)Solve an instance of the problem

In [1]:
import numpy as np
import numpy.random as npr
import math
import pandas as pd
import csv

In [2]:
def lineSerach(x,f,dx,g,t0 = 1.0, alpha = .5, beta = .5):    
    m = f(x)    
    k = alpha*dx.T@g  
    t = t0    
    for i in range(20):        
        if f(x+t*dx) > t*k+m:        
            t *= beta        
        else:            
            return t    
    else:        
        print("Warning: Line search did not converge.")        

In [3]:
def solve(Sigma, u, p, T0 = 1, mu = 10, eps = 1.0e-5, maxiter = 1000, alpha = 5, beta = .5):
    """ Solves 
    minimize: -p.T@x+mu*x.T@Sigma@x
    s.t. 1.T@x = 1
          x >= 0
          x is the optimal variabe"""
    n = p.size
    A = np.ones(n)[np.newaxis]#matrix A
    
    def f(z, T):
        """ Function """
        return T*(-p.T@z[:n]+u*z.T@Sigma@z[:n]) - np.sum(np.log(z))
    
    def g(z, T):
        """ Gardient """
        g = -T*p
        g += -1.0/z
        g[:n] += 2*T*u*Sigma@z[:n]
        return g
    
    def H(z,T):
        """ Hessian """
        h = np.diag(1.0/z**2)
        h[:n,:n]+= 2*T*u*Sigma
        return h
    
    # choosing the starting point i.e. sum of variable equal to 1 and non-negative
    z = np.ones(n)/n
    T = T0
    
    for i in range(maxiter):
        for j in range(maxiter):
            gz = g(z,T)#function call variable
            Hz = H(z,T)#function call variable
            M = np.vstack((np.hstack((Hz,A.T)),np.hstack((A,np.zeros((1,1))))))
            rhs = np.concatenate((-gz, np.zeros((1,))))#concatenate join a sequence of arrays along an existing axis
            dzv = np.linalg.solve(M,rhs)#solve a linear matrix equation linalg.solve
            dz = dzv[:n]
            l2 = -gz.T@dz
            if l2 < 2.0*eps:
                print(f'l2 = {l2}')
                break
            t =1.0
            
            while(np.amin(z+t*dz)<= 0.0): t *= beta
            t = lineSerach(z,lambda w: f(w,T),dz,gz,t,alpha = alpha, beta =beta)
            z += t*dz
        else:
            print("Warning: Solve did not converge.")
            return z[:n]
        if z.size/T < eps: return z[:n]
        T *= mu

# Data

In [4]:
data = pd.read_csv('data.csv') 
data.head()

Date    abb     vol     hm
0  Apr 01, 2020  168.4  112.85  123.1
1  Apr 02, 2020  170.8  114.95  115.1
2  Apr 03, 2020  168.8  112.10  114.0
3  Apr 06, 2020  176.9  121.00  126.0
4  Apr 07, 2020  181.9  128.50  134.9

In [5]:
# function to calculate daily simple returns
def getReturns(org):
    return (org- org.shift(1))*100/org.shift(1)

In [6]:
# function call
data['abb-Return'] = getReturns(data['abb'])
data['vol-Return'] = getReturns(data['vol'])
data['hm-Return'] = getReturns(data['hm'])

In [7]:
data.dropna(inplace=True)
data.head()

Date    abb     vol     hm  abb-Return  vol-Return  hm-Return
1  Apr 02, 2020  170.8  114.95  115.1    1.425178    1.860877  -6.498781
2  Apr 03, 2020  168.8  112.10  114.0   -1.170960   -2.479339  -0.955691
3  Apr 06, 2020  176.9  121.00  126.0    4.798578    7.939340  10.526316
4  Apr 07, 2020  181.9  128.50  134.9    2.826456    6.198347   7.063492
5  Apr 08, 2020  178.0  126.10  137.3   -2.144035   -1.867704   1.779096

In [8]:
# calculation of mean
p_abb=np.mean(data['abb-Return'])
p_vol=np.mean(data['vol-Return'])
p_hm=np.mean(data['hm-Return'])

# Portfolio

In [9]:
# Mean return of Portfolio
p = np.array([p_abb, p_vol, p_hm])
p

array([0.16455035, 0.27574645, 0.22412727])

In [10]:
#Size of Portfolio
n = np.size(p)
n

3

In [11]:
s_ABB = data['abb-Return']
s_vol = data['vol-Return']
s_hm = data['hm-Return']

# Covarinace Matrix of Portfolio

In [12]:
# computer portfolio covariance matrix
po = np.array([s_ABB, s_vol, s_hm])

We have n=3 so the Sigma which is the covariance of portfolio assets will be:

$$Sigma=\begin{bmatrix}\mathbb \sigma_{11} & \sigma_{12} & \sigma_{13}\\
\sigma_{21} & \sigma_{22} & \sigma_{23}\\
\sigma_{31} & \sigma_{32} & \sigma_{33}\\
\end{bmatrix}$$

In [13]:
Sigma= np.cov(po, bias =True)
print(Sigma)

[[ 8.53158581 10.63909276  3.85896829]
 [10.63909276 22.56998771  8.07761763]
 [ 3.85896829  8.07761763 26.5198713 ]]


$$Sigma=\begin{bmatrix} 
8.53158581 & 10.63909276 & 3.85896829\\
10.63909276 & 22.56998771 & 8.53158581\\
3.85896829 & 8.53158581 &26.5198713\\
\end{bmatrix}$$

# Output

In [14]:
u = 0.01
xsol = solve(Sigma, u, p, T0 = 1, mu = 10, eps = 1.0e-5, maxiter = 1000, alpha = .5, beta = .5)

l2 = 6.754693144768887e-06
l2 = 6.217568701012482e-06
l2 = 1.8140573088611383e-05
l2 = 2.058854582759307e-07
l2 = 1.781590812305594e-05
l2 = 1.3789308650727633e-16
l2 = 5.499062211117865e-15


In [15]:
xsol

array([0.44674595, 0.29619867, 0.25705538])

In [16]:
u = 0.000001
xsol = solve(Sigma, u, p, T0 = 1, mu = 10, eps = 1.0e-5, maxiter = 1000, alpha = .5, beta = .5)

l2 = 1.0696950753275371e-05
l2 = 1.2929777102419805e-05
l2 = 8.807408828756871e-06
l2 = 1.7346782078730148e-06
l2 = 7.236679115218796e-08
l2 = 1.744669417096112e-08
l2 = -3.698150314262018e-07


In [17]:
xsol

array([8.99405929e-06, 9.99971625e-01, 1.93811780e-05])

In [18]:
u = 100
xsol = solve(Sigma, u, p, T0 = 1, mu = 10, eps = 1.0e-5, maxiter = 1000, alpha = .5, beta = .5)

l2 = 7.308173793790806e-09
l2 = 6.507654652453771e-07
l2 = 5.695557237379292e-08
l2 = 1.2547002607223858e-08
l2 = 9.943897533836582e-09
l2 = -9.805662011611862e-09
l2 = -1.5319938551068915e-07


In [19]:
xsol

array([8.29040848e-01, 2.02583411e-09, 1.70959150e-01])

In [20]:
print(np.isclose(sum(xsol),1)) # Is the sum of the x-values close to 1 ?
print(np.all(xsol>0))#Are all x-values greater than 0 ?

True
True
